# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fedscale.cloud.channels import job_api_pb2 as fedscale_dot_cloud_dot_channels_dot_job__api__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fedscale/cloud/channels/job_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CLIENT_REGISTER = channel.unary_unary(
                '/fedscale.JobService/CLIENT_REGISTER',
                request_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.RegisterRequest.SerializeToString,
                response_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.CLIENT_PING = channel.unary_unary(
                '/fedscale.JobService/CLIENT_PING',
                request_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.PingRequest.SerializeToString,
                response_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.CLIENT_EXECUTE_COMPLETION = channel.unary_unary(
                '/fedscale.JobService/CLIENT_EXECUTE_COMPLETION',
                request_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.CompleteRequest.SerializeToString,
                response_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.GetAggregatorStatus = channel.unary_unary(
                '/fedscale.JobService/GetAggregatorStatus',
                request_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.StatusRequest.SerializeToString,
                response_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.StatusReply.FromString,
                _registered_method=True)
        self.GetRoundMetrics = channel.unary_unary(
                '/fedscale.JobService/GetRoundMetrics',
                request_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.MetricsRequest.SerializeToString,
                response_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.MetricsReply.FromString,
                _registered_method=True)


class JobServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CLIENT_REGISTER(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CLIENT_PING(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CLIENT_EXECUTE_COMPLETION(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregatorStatus(self, request, context):
        """Dashboard endpoints:
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoundMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CLIENT_REGISTER': grpc.unary_unary_rpc_method_handler(
                    servicer.CLIENT_REGISTER,
                    request_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.RegisterRequest.FromString,
                    response_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.SerializeToString,
            ),
            'CLIENT_PING': grpc.unary_unary_rpc_method_handler(
                    servicer.CLIENT_PING,
                    request_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.PingRequest.FromString,
                    response_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.SerializeToString,
            ),
            'CLIENT_EXECUTE_COMPLETION': grpc.unary_unary_rpc_method_handler(
                    servicer.CLIENT_EXECUTE_COMPLETION,
                    request_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.CompleteRequest.FromString,
                    response_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.SerializeToString,
            ),
            'GetAggregatorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregatorStatus,
                    request_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.StatusRequest.FromString,
                    response_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.StatusReply.SerializeToString,
            ),
            'GetRoundMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoundMetrics,
                    request_deserializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.MetricsRequest.FromString,
                    response_serializer=fedscale_dot_cloud_dot_channels_dot_job__api__pb2.MetricsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedscale.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedscale.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CLIENT_REGISTER(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/CLIENT_REGISTER',
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.RegisterRequest.SerializeToString,
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CLIENT_PING(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/CLIENT_PING',
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.PingRequest.SerializeToString,
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CLIENT_EXECUTE_COMPLETION(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/CLIENT_EXECUTE_COMPLETION',
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.CompleteRequest.SerializeToString,
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAggregatorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/GetAggregatorStatus',
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.StatusRequest.SerializeToString,
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoundMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/GetRoundMetrics',
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.MetricsRequest.SerializeToString,
            fedscale_dot_cloud_dot_channels_dot_job__api__pb2.MetricsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
